### ISSUE TITLE
Libguide page

### ISSUE THREAD

**Issue by ericrobskyhuntley** [bplmaps/lane-mead-portal#26]
Develop a libguides page that will serve to introduce objects/collections referenced in a given portal. See e.g., https://guides.bpl.org/bpldocs for example of standard libguide.

N.b., we're not trying to duplicate all functionality, just create a source for users intending to access collections.

**Comment by garrettdashnelson** [comment]
Some notes:

* Let's use the nomenclature "Research Guides" for these and route them to `/research/[slug].astro`
* My suggestion (and it is only a suggestion) would be for the content of this type to be written in Markdoc format, and to use the [@astrojs/markdoc](https://docs.astro.build/en/guides/integrations-guide/markdoc/) integration to parse it.
* I'm less convinced about this suggestion, but the [Astro Starlight](https://starlight.astro.build/manual-setup/) template is Astro's own in-house documentation template, and it can be added to an existing site. It may be worth evaluating whether using Starlight outright, or borrowing from it, is worthwhile.
