### ISSUE TITLE
Create working "Discover" (e.g., story-essay-theme) page type

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/lane-mead-portal#4]
![Scanned from a Xerox Multifunction Printer001](https://github.com/bplmaps/lane-mead-portal/assets/2424901/af4a5e75-263c-437a-abf3-aff526165ec6)

**Comment by ericrobskyhuntley** [comment]
Working page type as of 06f4530 (or earlier - thanks, @garrettdashnelson )
